# version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: resume_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: resume_processing
      MYSQL_USER: resume_user
      MYSQL_PASSWORD: resume_password
    ports:
      - "3305:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    #- ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - resume_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:

networks:
  resume_network:
    driver: bridge
