import pandas as pd
df = pd.read_pickle('../data/clean_42k_v1.pkl')
print('=== TRAINING DATA SUMMARY (clean_42k_v1.pkl) ===')
print(f'Records: {len(df):,}')
print(f'Companies: {df.company_name.nunique()}')
print(f'Date range: {df.issue_date.min().date()} to {df.issue_date.max().date()}')
print(f'Regions: {df.region.value_counts().to_dict()}')
print(f'Columns: {df.columns.tolist()}')
print()
print('=== TOP 20 COMPANIES BY OPENINGS ===')
top = df.groupby('company_name')['openings'].sum().sort_values(ascending=False).head(20)
for c, v in top.items():
    print(f'  {c}: {v:,}')
print()
gap_count = len(df[df['company_name'] == 'Gap Inc'])
print('=== DATA SOURCES INCLUDED ===')
print(f'1. JobDiva historical (cleaned from 190k raw): bulk of records')
print(f'2. Gap Inc Excel (438 reqs): {gap_count} records in training')
print(f'3. Career page gap-fills (synthetic): ~967 imputed records for continuity')
print()
yr = pd.to_datetime(df['issue_date']).dt.year.value_counts().sort_index()
print('=== RECORDS BY YEAR ===')
for y, c in yr.items():
    print(f'  {y}: {c:,}')
print()
print('=== SAMPLE ROW ===')
print(df.iloc[0].to_dict())
